### ISSUE TITLE
Pending migrations bug?

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/spotlight#1136]
After pulling current code and generating a fresh app, when I start Rails I get a pending migrations error. Since I haven't seen this before (and it seems that all migrations should be taken care of when running enginecart:generate?), I'm guessing this is a bug?

Here's the initial part of the output when starting Rails:

> => Booting WEBrick
=> Rails 4.2.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2015-04-17 13:10:12] INFO  WEBrick 1.3.1
[2015-04-17 13:10:12] INFO  ruby 2.1.3 (2014-09-19) [x86_64-darwin14.0]
[2015-04-17 13:10:12] INFO  WEBrick::HTTPServer#start: pid=16250 port=3000

> Started GET "/" for ::1 at 2015-04-17 13:10:18 -0700
  ActiveRecord::SchemaMigration Load (0.2ms)  SELECT "schema_migrations".* FROM "schema_migrations"

> ActiveRecord::PendingMigrationError (

> Migrations are pending. To resolve this issue, run:

>	bin/rake db:migrate RAILS_ENV=development

**Comment by ggeisler** [comment]
Here's the point where the migration fails when running enginecart:

````
== 20150422182731 AddTaggingsCounterCacheToTags: migrating ====================
-- add_column(:tags, :taggings_count, :integer, {:default=>0})
   -> 0.0006s
== 20150422182731 AddTaggingsCounterCacheToTags: migrated (0.0025s) ===========

== 20150422182732 AddMissingTaggableIndex: migrating ==========================
-- add_index(:taggings, [:taggable_id, :taggable_type, :context])
   -> 0.0008s
== 20150422182732 AddMissingTaggableIndex: migrated (0.0009s) =================

== 20150422182733 ChangeCollationForTagNames: migrating =======================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `using_mysql?' for ActsAsTaggableOn::Utils:Module/Users/geisler/Sites/stanford/spotlight/spec/internal/db/migrate/20150422182733_change_collation_for_tag_names.spotlight.rb:7:in `up'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:609:in `exec_migration'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:589:in `block in migrate'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:588:in `migrate'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:765:in `migrate'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:1041:in `ddl_transaction'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:956:in `block in migrate'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `each'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `migrate'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:820:in `up'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:798:in `migrate'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
NoMethodError: undefined method `using_mysql?' for ActsAsTaggableOn::Utils:Module
/Users/geisler/Sites/stanford/spotlight/spec/internal/db/migrate/20150422182733_change_collation_for_tag_names.spotlight.rb:7:in `up'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:609:in `exec_migration'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:589:in `block in migrate'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:588:in `migrate'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:765:in `migrate'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:1041:in `ddl_transaction'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:956:in `block in migrate'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `each'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `migrate'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:820:in `up'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/migration.rb:798:in `migrate'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/geisler/.rvm/gems/ruby-2.1.3@global/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
    generate  spotlight:install
       route  mount Spotlight::Engine, at: 'spotlight'

````

**Comment by ggeisler** [comment]
@cbeer @jkeck Although we couldn't fix this via bundle updates, completely re-cloning Spotlight did enable me to get updated to the 3.5 version of acts-as-taggable-on. So I'm going to assume it was just some weird local problem and close this issue.
