### ISSUE TITLE
Installing from template gives bundler warnings

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/spotlight#1339]
```
$ rake rails:template LOCATION=https://raw.githubusercontent.com/sul-dlss/spotlight/master/template.rb
     gemfile  blacklight (~> 5.16)
     gemfile  blacklight-spotlight
         run  bundle install from "."
The git source git://github.com/sul-dlss/spotlight.git is not yet checked out. Please run `bundle install` before trying to start your application
    generate  blacklight:install
The git source git://github.com/sul-dlss/spotlight.git is not yet checked out. Please run `bundle install` before trying to start your application
    generate  spotlight:install
The git source git://github.com/sul-dlss/spotlight.git is not yet checked out. Please run `bundle install` before trying to start your application
        rake  spotlight:install:migrations
The git source git://github.com/sul-dlss/spotlight.git is not yet checked out. Please run `bundle install` before trying to start your application
Would you like to create an initial administrator? yes
        rake  db:migrate
The git source git://github.com/sul-dlss/spotlight.git is not yet checked out. Please run `bundle install` before trying to start your application
        rake  spotlight:initialize
The git source git://github.com/sul-dlss/spotlight.git is not yet checked out. Please run `bundle install` before trying to start your application
        rake  jetty:configure_solr
The git source git://github.com/sul-dlss/spotlight.git is not yet checked out. Please run `bundle install` before trying to start your application
```

**Comment by jcoyne** [comment]
Installing in this manner seems to work:

```
rails new app-name -m https://raw.githubusercontent.com/sul-dlss/spotlight/master/template.rb
```

but I get sitemap_generator warnings like this:
```
Could not find gem 'sitemap_generator (>= 0) ruby' in any of the gem sources listed in your Gemfile or available on this machine.
```

Possibly because it doesn't `bundle install` after the `     gemfile  sitemap_generator` step.

**Comment by jcoyne** [comment]
Scratch that. The second method doesn't work either. Many of the generators were skipped culminating in a `Could not find table 'spotlight_roles'` when I start up the site.  Here's the gist https://gist.github.com/jcoyne/d24ba66170571eb3d908

**Comment by jcoyne** [comment]
It seems to work if you run `gem install sitemap_generator` prior to creating the new app.

**Comment by anjackson** [comment]
Not sure if this is the same problem, but I just tried to set an app up from the template, and it failed with this error

    https://raw.githubusercontent.com/projectblacklight/spotlight/master/template.rb:10:in `apply': uninitialized constant Rails::Generators::AppGenerator::Bundler (NameError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:223:in `instance_eval'
    ....

See attached for full details: [spotlight-setup-error.txt](https://github.com/projectblacklight/spotlight/files/222830/spotlight-setup-error.txt)
