### ISSUE TITLE
Error on uploading a picture

### ISSUE THREAD

**Issue by ronan-mch** [sul-dlss/spotlight#1350]
```
ActionView::Template::Error (undefined method `attachments_path' for #<#<Class:0x007f9218399728>:0x007f92183889c8>):
    1: <%= form_for(@attachment) do |f| %>
    2:   <% if @attachment.errors.any? %>
    3:     <div id="error_explanation">
    4:       <h2><%= pluralize(@attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>
  /home/ronan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/spotlight-650ceb04e722/app/helpers/spotlight/application_helper.rb:27:in `method_missing'
  actionpack (4.2.5) lib/action_dispatch/routing/polymorphic_routes.rb:220:in `polymorphic_method'
  actionpack (4.2.5) lib/action_dispatch/routing/polymorphic_routes.rb:134:in `polymorphic_path'
  actionview (4.2.5) lib/action_view/helpers/form_helper.rb:466:in `apply_form_for_options!'
  actionview (4.2.5) lib/action_view/helpers/form_helper.rb:434:in `form_for'
  /home/ronan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/spotlight-650ceb04e722/app/views/spotlight/attachments/_form.html.erb:1:in `__home_ronan__rbenv_versions_______lib_ruby_gems_______bundler_gems_spotlight____ceb__e____app_views_spotlight_attachments__form_html_erb___962998000907324687_70132723733000'
  actionview (4.2.5) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.5) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.5) lib/action_view/template.rb:333:in `instrument'
```

**Comment by jcoyne** [comment]
We're seeing this error because we're ending up on this path: https://github.com/sul-dlss/spotlight/commit/bc6025a7caa9f08652db7fabd03dfd78ce3eeece

We have an error (due to imagemagick not being installed).  I'm wondering if we should just be doing save! there and throwing the error. Is that failure path used elsewhere?  Given that we're seeing the undefined method error :point_up_2: I would suspect not.

**Comment by cbeer** [comment]
Failing hard sounds good -- I don't think we expected anyone to end up there anyway. That said, it seems like something we could also try to just fix.
