### ISSUE TITLE
Authenticity token errors when uploading images to exhibits

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/spotlight#863]
```
Started POST "/maps-of-africa/spotlight/default-exhibit/attachments" for 171.66.18.186 at 2015-01-15 08:51:53 -0800
Processing by Spotlight::AttachmentsController#create as JSON
  Parameters: {"attachment"=>{"name"=>"large_cartouche_sanson_maps.JPG", "file"=>#<ActionDispatch::Http::UploadedFile:0x000000076bc1d0 @tempfile=#<Tempfile:/tmp/RackMultipart20150115-18759-11hrppv.JPG>, @original_filename="large_cartouche_sanson_maps.JPG", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"attachment[file]\"; filename=\"large_cartouche_sanson_maps.JPG\"\r\nContent-Type: image/jpeg\r\n">, "uid"=>"st-block-12-1421340713309-raw"}, "exhibit_id"=>"default-exhibit"}
Can't verify CSRF token authenticity
Completed 422 Unprocessable Entity in 4ms

ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
  actionpack (4.2.0) lib/action_controller/metal/request_forgery_protection.rb:181:in `handle_unverified_request'
  actionpack (4.2.0) lib/action_controller/metal/request_forgery_protection.rb:209:in `handle_unverified_request'
  devise (3.4.1) lib/devise/controllers/helpers.rb:251:in `handle_unverified_request'
  actionpack (4.2.0) lib/action_controller/metal/request_forgery_protection.rb:204:in `verify_authenticity_token'
  activesupport (4.2.0) lib/active_support/callbacks.rb:427:in `block in make_lambda'
  activesupport (4.2.0) lib/active_support/callbacks.rb:163:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:163:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `call'
```

**Comment by cbeer** [comment]
Fixed by giving each exhibit a custom session store key prefix.
